name: Build Release Packages
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    name: Create and Publish Artifacts
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os: [Linux, Windows]
        arch: [32-bit, 64-bit]
        exclude:
          - os: Linux
            arch: 32-bit
        include:
          - os: Windows
            arch: Slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Dist Packages
        run: make dist
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Upload ${{ matrix.os }} ${{ matrix.arch }} Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/artifacts/GuideMe.${{ matrix.os }}.${{ matrix.arch }}.zip
          asset_name: GuideMe-${github.ref#refs/tags/}-${{ matrix.os }}.${{ matrix.arch }}.zip
          asset_content_type: application/zip